### ISSUE TITLE
It appears that the calculation for point inside is not correct when the button image dimensions do not match the button size dimensions

### ISSUE THREAD

**Issue by jayson-h** [ole/OBShapedButton#1]
It appears that the code does not account for image sizes that do not match the button size (probably only applies to development builds as production images should match the button size).

I added the following logic inside of "pointInside" to account for image sizes that do not match the button size (I did not test for Retina Display @2x images).  You may be able to design something more elegant.

```
CGSize iSize = buttonImage.size;
CGSize bSize = self.frame.size;
point.x *= (bSize.width != 0) ? (iSize.width / bSize.width) : 1;
point.y *= (bSize.height != 0) ? (iSize.height / bSize.height) : 1;
```

**Comment by pppqppqpphejj** [comment]
handsome boy ，this is there Swift  version

**Comment by ole** [comment]
@pppqppqpphejj No. See #11 for an explanation.
