### ISSUE TITLE
The version 1.2.0 is not yet in CocoaPods, the latest one is 1.1.0.

### ISSUE THREAD

**Issue by Algalish** [ole/OBShapedButton#15]
I am surprised that over 2 years I am the first one, who discovered this)

**Comment by ole** [comment]
@Algalish Thanks for telling me and sorry. I just published [1.2.0](https://github.com/ole/OBShapedButton/releases/tag/1.2.0) [on CocoaPods](https://cocoapods.org/pods/OBShapedButton).
